# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_level',
            field=models.CharField(choices=[('o', 'owner'), ('u', 'user')], max_length=1, null=True),
        ),
    ]
