# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161019_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operation',
            new_name='Operation_obj',
        ),
    ]
